import type { CliSignature } from "./types.js";

/**
 * 已知 AI 厂商 CLI / 相关工具的签名注册表（macOS 优先）。
 * 添加新条目的原则：
 *  - 只列**明确存在**的官方 / 主流工具，宁缺毋滥（不臆造，见 AGENTS.md）；
 *  - probe 顺序：优先 `which`（PATH 中），再 macOS `/Applications` 的 .app 包，最后 Homebrew formula；
 *  - agentUsage 一句话写清"挂到 Agent 上有什么用"，让用户在创建 Agent 时能判断要不要挂载。
 * R2 待补：Windows / Linux 的路径与 probe；用户自定义 CLI 白名单（yaml 声明）。
 */
export const MAC_CLI_REGISTRY: CliSignature[] = [
  {
    id: "anthropic-claude-code",
    name: "Claude Code",
    vendor: "Anthropic",
    category: "agent-cli",
    homepage: "https://docs.claude.com/en/docs/claude-code/overview",
    description: "Anthropic 官方终端 Coding Agent，支持仓库级理解与多轮工具调用。",
    agentUsage: "让 Agent 通过 Claude Code 在本机仓库里执行编码类子任务（需 Anthropic API Key 或订阅）。",
    probes: [
      { kind: "which", bin: "claude" },
      { kind: "appBundle", path: "/Applications/Claude.app" },
    ],
    versionCmd: ["claude", "--version"],
    suggestInstall: "npm i -g @anthropic-ai/claude-code   # 或 brew install claude-code",
  },
  {
    id: "openai-codex-cli",
    name: "OpenAI Codex CLI",
    vendor: "OpenAI",
    category: "agent-cli",
    homepage: "https://github.com/openai/codex",
    description: "OpenAI 官方终端 Coding Agent（Codex），沙箱式执行代码与工具调用。",
    agentUsage: "让 Agent 通过 Codex CLI 在本机做编码 / 重构 / 修 bug 类子任务（需 OpenAI API Key）。",
    probes: [{ kind: "which", bin: "codex" }],
    versionCmd: ["codex", "--version"],
    suggestInstall: "npm i -g @openai/codex   # 或 brew install codex",
  },
  {
    id: "google-gemini-cli",
    name: "Gemini CLI",
    vendor: "Google",
    category: "agent-cli",
    homepage: "https://github.com/google-gemini/gemini-cli",
    description: "Google 官方 Gemini 终端 Agent，支持工具调用与长上下文。",
    agentUsage: "让 Agent 通过 Gemini CLI 调用 Google 系列模型做研究 / 编码 / 分析子任务。",
    probes: [{ kind: "which", bin: "gemini" }],
    versionCmd: ["gemini", "--version"],
    suggestInstall: "npm i -g @google/gemini-cli",
  },
  {
    id: "openai-cli",
    name: "OpenAI CLI",
    vendor: "OpenAI",
    category: "chat-cli",
    homepage: "https://github.com/openai/openai-python",
    description: "OpenAI Python 官方 CLI（`openai`），非 Agent 类，主要用于 API 一次性调用。",
    agentUsage: "让 Agent 通过 openai CLI 单轮调用 GPT 系列模型（无工具调用），适合机械性文本任务。",
    probes: [{ kind: "which", bin: "openai" }],
    versionCmd: ["openai", "--version"],
    suggestInstall: "pipx install openai   # 或 pip install --user openai",
  },
  {
    id: "ollama",
    name: "Ollama",
    vendor: "Ollama",
    category: "runtime",
    homepage: "https://ollama.com",
    description: "本机运行开源大模型的 runtime（Llama / Qwen / DeepSeek 等）。",
    agentUsage: "让 Agent 用本机模型执行任务，数据不出内网（配合 模型接入 里 OpenAI 兼容 Base URL `http://localhost:11434/v1`）。",
    probes: [
      { kind: "which", bin: "ollama" },
      { kind: "appBundle", path: "/Applications/Ollama.app" },
    ],
    versionCmd: ["ollama", "--version"],
    suggestInstall: "brew install ollama   # 或从 https://ollama.com 下载",
  },
  {
    id: "aider",
    name: "Aider",
    vendor: "aider.chat",
    category: "agent-cli",
    homepage: "https://aider.chat",
    description: "开源终端 Coding Agent，支持 Git 集成与多模型后端。",
    agentUsage: "让 Agent 用 Aider 在本机仓库做多文件编辑 / 重构类子任务。",
    probes: [{ kind: "which", bin: "aider" }],
    versionCmd: ["aider", "--version"],
    suggestInstall: "pipx install aider-chat   # 或 pip install --user aider-chat",
  },
  {
    id: "github-copilot-cli",
    name: "GitHub Copilot CLI",
    vendor: "GitHub",
    category: "chat-cli",
    homepage: "https://docs.github.com/en/copilot/github-copilot-in-the-cli",
    description: "GitHub Copilot 的终端扩展（作为 `gh` 的子命令）。",
    agentUsage: "让 Agent 借用 Copilot 建议进行 shell / git 相关问答（需 Copilot 订阅）。",
    probes: [{ kind: "which", bin: "gh" }],
    versionCmd: ["gh", "--version"],
    suggestInstall: "brew install gh && gh extension install github/gh-copilot",
  },
  {
    id: "amazon-q-cli",
    name: "Amazon Q Developer CLI",
    vendor: "Amazon",
    category: "chat-cli",
    homepage: "https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/command-line.html",
    description: "AWS Amazon Q Developer 的终端集成（`q`）。",
    agentUsage: "让 Agent 通过 Amazon Q 完成 AWS 场景问答 / 命令建议（需 Builder ID）。",
    probes: [
      { kind: "which", bin: "q" },
      { kind: "appBundle", path: "/Applications/Amazon Q.app" },
    ],
    versionCmd: ["q", "--version"],
    suggestInstall: "brew install --cask amazon-q",
  },
  {
    id: "cursor-ide",
    name: "Cursor",
    vendor: "Anysphere",
    category: "ide-companion",
    homepage: "https://cursor.com",
    description: "AI-native IDE（VS Code 分支）。检测到即可用其 `cursor` CLI 打开工作区。",
    agentUsage: "让 Agent 把编辑意图交给 Cursor 打开对应位置，人工在 IDE 里最终确认（合规友好）。",
    probes: [
      { kind: "appBundle", path: "/Applications/Cursor.app" },
      { kind: "which", bin: "cursor" },
    ],
    versionCmd: ["cursor", "--version"],
    suggestInstall: "brew install --cask cursor",
  },
  {
    id: "lm-studio",
    name: "LM Studio",
    vendor: "LM Studio",
    category: "runtime",
    homepage: "https://lmstudio.ai",
    description: "本机开源模型 GUI，兼容 OpenAI 协议提供本地服务。",
    agentUsage: "同 Ollama，走\"模型接入\"里的 OpenAI 兼容 Base URL（默认 `http://localhost:1234/v1`）。",
    probes: [{ kind: "appBundle", path: "/Applications/LM Studio.app" }],
    suggestInstall: "从 https://lmstudio.ai 下载安装",
  },
];
